#include "PluginProcessor.h"
#include <iostream>
#include <memory>
#include <stdexcept>
#include <set>
using P=MonomachineNovaAudioProcessor;
static void check(bool v,const char* why){if(!v)throw std::runtime_error(why);}
static void set(P& p,const juce::String& id,float value){auto* a=p.parameters.getParameter(id);check(a!=nullptr,"missing parameter");a->setValueNotifyingHost(a->convertTo0to1(value));}
static juce::Button* button(juce::Component& c,const juce::String& text){if(auto* b=dynamic_cast<juce::Button*>(&c))if(b->getButtonText()==text||(text=="ARP"&&b->getButtonText().startsWith("ARP ")))return b;for(auto* child:c.getChildren())if(auto* b=button(*child,text))return b;return nullptr;}
static juce::Component* named(juce::Component& c,const juce::String& name){if(c.getName()==name)return &c;for(auto* child:c.getChildren())if(auto* found=named(*child,name))return found;return nullptr;}
static juce::Viewport* viewport(juce::Component& c){if(auto* v=dynamic_cast<juce::Viewport*>(&c))if(v->getWidth()>1000)return v;for(auto* child:c.getChildren())if(auto* v=viewport(*child))return v;return nullptr;}
static juce::Slider* lfoSpeed(juce::Component& c){if(auto* s=dynamic_cast<juce::Slider*>(&c)){auto* parent=s->getParentComponent();if(parent&&parent->getX()==969&&parent->getY()==466)return s;}for(auto* ch:c.getChildren())if(auto* s=lfoSpeed(*ch))return s;return nullptr;}
static juce::Slider* ampDecaySlider(juce::Component& c){if(auto* sl=dynamic_cast<juce::Slider*>(&c)){auto* p=sl->getParentComponent();if(p&&p->getX()==666&&p->getY()==130)return sl;}for(auto* ch:c.getChildren())if(auto* sl=ampDecaySlider(*ch))return sl;return nullptr;}
static juce::FileDragAndDropTarget* dropTarget(juce::Component& c,const juce::StringArray& files){if(auto* d=dynamic_cast<juce::FileDragAndDropTarget*>(&c))if(d->isInterestedInFileDrag(files))return d;for(auto* ch:c.getChildren())if(auto* d=dropTarget(*ch,files))return d;return nullptr;}
static void saveImage(juce::Component& c,const juce::String& path){auto file=juce::File::getCurrentWorkingDirectory().getChildFile(path);file.deleteFile();auto stream=file.createOutputStream();check(stream!=nullptr,"snapshot output");juce::PNGImageFormat png;check(png.writeImageToStream(c.createComponentSnapshot(c.getLocalBounds()),*stream),"snapshot write");}
static double compareAudio(P& a,P& b){a.prepareToPlay(48000,128);b.prepareToPlay(48000,128);juce::AudioBuffer<float> ba(2,128),bb(2,128);double d=0;
    for(int block=0;block<300;++block){ba.clear();bb.clear();juce::MidiBuffer ma,mb;if(block==0){ma.addEvent(juce::MidiMessage::noteOn(1,60,static_cast<juce::uint8>(100)),0);mb=ma;}a.processBlock(ba,ma);b.processBlock(bb,mb);for(int i=0;i<128;++i){check(std::isfinite(ba.getSample(0,i))&&std::isfinite(bb.getSample(0,i)),"nonfinite render");d+=std::abs(ba.getSample(0,i)-bb.getSample(0,i));}}return d;
}
#include "AmpChecks.h"

static void checkFx142(){
 if(P::isSynthVersion)return;
 for(double rate:{44100.0,48000.0})for(int gate:{0,1})for(int wet:{0,127}){
  auto p=std::make_unique<P>();set(*p,"gate",static_cast<float>(gate));set(*p,"fx_mix",static_cast<float>(wet));set(*p,"p0_1",127);set(*p,"p0_3",0);p->prepareToPlay(rate,128);
  double input=0,output=0,early=0,active=0;int midiCount=0;
  for(int block=0;block<600;++block){juce::AudioBuffer<float> b(2,128);for(int i=0;i<128;++i){float v=0.1f*std::sin(static_cast<float>(2*nova::pi*1000*(block*128+i)/rate));b.setSample(0,i,v);b.setSample(1,i,v);if(block>=500)input+=v*v;}
   juce::MidiBuffer m;if(block==10)m.addEvent(juce::MidiMessage::noteOn(1,72,static_cast<juce::uint8>(20)),17);if(block==20)m.addEvent(juce::MidiMessage::noteOff(1,72),71);p->processBlock(b,m);midiCount+=m.getNumEvents();
   for(int i=0;i<128;++i){const double v=b.getSample(0,i);check(std::isfinite(v),"FX 142 nonfinite");if(block<9)early+=v*v;if(block>11&&block<19)active+=v*v;if(block>=500)output+=v*v;}
  }
  check(midiCount==2,"MIDI lost in latch/gate");check(active>0.000001,"MIDI gate never opened");double ratio=std::sqrt(output/input);
  if(gate){check(early<1e-10,"MIDI gate leaks before first note");check(ratio<0.0001,"MIDI gate leaks after release (including dry)");}
  else check(std::abs(ratio-1)<0.01,"FX defaults not unity / latch closed by MIDI");
  std::cout<<"FX142 sr="<<rate<<" midi="<<gate<<" mix="<<wet<<" late ratio="<<ratio<<" PASS\n";
 }
}


static void allMachineSmoke(){int cases=0;
 for(double sr:{44100.0,48000.0,96000.0})for(int channels:{1,2}){
  auto p=std::make_unique<P>();auto layout=p->getBusesLayout();auto set=channels==1?juce::AudioChannelSet::mono():juce::AudioChannelSet::stereo();layout.outputBuses.set(0,set);if(!P::isSynthVersion)layout.inputBuses.set(0,set);check(p->setBusesLayout(layout),"mono/stereo layout rejected");
  for(size_t machine=0;machine<nova::machines().size();++machine){::set(*p,"machine",static_cast<float>(machine));p->prepareToPlay(sr,128);
   for(int block=0;block<24;++block){juce::AudioBuffer<float> b(channels,128);for(int ch=0;ch<channels;++ch)for(int i=0;i<128;++i)b.setSample(ch,i,P::isSynthVersion?0.0f:0.1f*std::sin(static_cast<float>((block*128+i)*0.07)));
    juce::MidiBuffer midi;if(block==0||block==16)midi.addEvent(juce::MidiMessage::noteOn(1,60,static_cast<juce::uint8>(100)),7);if(block==8)midi.addEvent(juce::MidiMessage::noteOff(1,60),31);const int count=midi.getNumEvents();p->processBlock(b,midi);check(midi.getNumEvents()==(P::isSynthVersion?0:count),"machine MIDI contract");for(int ch=0;ch<channels;++ch)for(int i=0;i<128;++i)check(std::isfinite(b.getSample(ch,i)),"nonfinite machine output");
   }p->releaseResources();++cases;
  }
 }std::cout<<"All machine smoke: "<<cases<<" machine/rate/layout cases PASS\n";
}


static std::vector<float> renderMachine(int id,std::array<float,8> params){nova::MachineEngine e;e.prepare(44100);e.set(id,params);e.setPitch(60,0);e.on(60);std::vector<float> l(16384),r(16384);e.render(l.data(),r.data(),16384,true);return l;}
static double energy(const std::vector<float>& x){double e=0;for(float f:x)e+=f*f;return e;}
static void dsp1Checks(P& p){
 {nova::NoiseContour f;f.prepare(44100);struct Test{size_t profile;double hz,target;};for(auto t:{Test{0,30,-38},Test{0,13500,0},Test{1,3500,-16},Test{2,22,-16},Test{2,180,-22},Test{2,10000,-29},Test{3,3700,-29},Test{3,11800,-29}}){double v=f.magnitudeDb(t.profile,t.hz);std::cout<<"NOISE contour "<<t.profile<<" @"<<t.hz<<": "<<v<<" dB / target "<<t.target<<"\n";check(std::abs(v-t.target)<1,"NOISE anchor outside 1 dB tolerance");}}
 {std::array<float,8> a{0,0,0,1,0,0,0,64};auto base=renderMachine(4,a);a[0]=127;a[2]=127;auto widthZero=renderMachine(4,a);check(base==widthZero,"UNIW zero leaves extra voices");a[0]=0;a[1]=127;auto levelZero=renderMachine(4,a);check(base==levelZero,"UNIL zero leaves extra voices");a={0,0,0,0,0,0,0,64};auto legacy=renderMachine(4,a);double ratio=std::sqrt(energy(base)/energy(legacy));check(ratio>0.05&&ratio<0.14,"SAW trim");a[3]=1;a[5]=127;auto sub1=renderMachine(4,a);a[5]=0;a[6]=127;auto sub2=renderMachine(4,a);a[6]=0;a[4]=127;auto dirty=renderMachine(4,a);check(sub1!=sub2&&sub1!=dirty,"sub voices identical");std::cout<<"SAW new/legacy RMS ratio="<<ratio<<" PASS\n";}
 {monomachine::MonomachineBBox b;b.reset(44100);std::array<float,8> pulse{0,1,0,0,0,0,0,0};b.loadSample(0,"pulse",pulse.data(),pulse.size());b.setParameters(64,0,1,1);const size_t interval=b.retriggerInterval();check(interval>11000,"RTIM 1 must be long");b.noteOn(48);std::vector<float> l(interval+20),r(l.size());b.processStereo(l.data(),r.data(),l.size());int hits=0;for(float v:l)if(v>0.001f)++hits;check(hits==2,"RTRG1 is not exactly one repeat");check(std::abs(20*std::log10(l[interval+1]/l[1])+15)<0.01,"repeat attenuation");b.setParameters(64,0,1,127);check(b.retriggerInterval()>=200&&b.retriggerInterval()<=441,"RTIM 127 must be about 5 ms, not zero");b.setParameters(64,0,127,110);size_t step=b.retriggerInterval();b.noteOn(48);std::vector<float> many(step*127+20),mr(many.size());b.processStereo(many.data(),mr.data(),many.size());check(std::abs(20*std::log10(many[step*127+1]/many[1])+15)<0.02,"long retrigger tail not attenuated");for(size_t i=1;i<=127;++i)check(many[step*i+1]<many[step*(i-1)+1],"repeat series not decaying");
  std::vector<float> hit(22050);for(size_t i=0;i<hit.size();++i)hit[i]=std::exp(-static_cast<float>(i)/(44100*.025f));b.loadSample(0,"hit",hit.data(),hit.size());b.setParameters(64,48,0,0);check(b.startPosition(b.getSlots()[0])<441,"START48 skips too much");
  monomachine::MonomachineBBox old(false),modern(true);check(old.getSlots()[7].data==modern.getSlots()[7].data&&old.getSlots()[23].data==modern.getSlots()[23].data,"approved bell/zap changed");for(size_t i:{size_t(1),size_t(2),size_t(3)})check(old.getSlots()[i].data!=modern.getSlots()[i].data,"new snare/toms missing from the working kit");for(size_t i:{size_t(0),size_t(5),size_t(12),size_t(14),size_t(16)})check(old.getSlots()[i].data==modern.getSlots()[i].data,"working kit must keep the old voice");}
 if(P::isSynthVersion){check(p.parameters.getParameter("m2_3")&&p.parameters.getParameter("m2_4"),"NOISE TIME/BIT not registered");check(p.parameters.getParameter("m4_3")->getAllValueStrings().joinIntoString("|")=="LEGACY|RETRO","SAW MODE missing");check(p.parameters.getParameter("m2_3")->getText(p.parameters.getParameter("m2_3")->getDefaultValue(),32)=="0","TIME does not display zero");}
 {std::array<float,8> x{0,0,0,64,0,0,0,64};const auto start=juce::Time::getMillisecondCounterHiRes();auto normal=renderMachine(2,x);double elapsed=juce::Time::getMillisecondCounterHiRes()-start;x[3]=48;auto shorter=renderMachine(2,x);x[3]=80;auto longer=renderMachine(2,x);size_t n=12000;double expected=std::exp(-(static_cast<double>(n)/44100)/0.2489085587);check(std::abs(shorter[n]/normal[n]-expected)<0.001,"NOISE TIME shorter rate");check(std::abs(longer[n]/normal[n]-1/std::sqrt(expected))<0.001,"NOISE TIME longer rate");x[3]=64;x[4]=127;check(renderMachine(2,x)!=normal,"BIT has no audio effect");std::cout<<"NOISE 16384 frames incl engine setup: "<<elapsed<<" ms (not a host CPU benchmark)\n";}
 if(P::isSynthVersion){auto original=p.parameters.copyState();auto legacy=original.createCopy();legacy.setProperty("schema",5,nullptr);for(const char* id:{"m4_3","m2_3","m2_4"}){auto child=legacy.getChildWithProperty("id",id);if(child.isValid())legacy.removeChild(child,nullptr);}legacy.getChildWithProperty("id","m2_1").setProperty("value",101.0f,nullptr);auto xml=legacy.createXml();juce::MemoryBlock data;P::copyXmlToBinary(*xml,data);p.setStateInformation(data.getData(),static_cast<int>(data.getSize()));check(p.parameters.getRawParameterValue("m2_4")->load()==101&&p.parameters.getRawParameterValue("m2_1")->load()==0,"old Redux migration failed");check(p.parameters.getRawParameterValue("m4_3")->load()==0&&p.parameters.getRawParameterValue("m2_3")->load()==64,"legacy SAW / neutral TIME migration failed");
 if(P::isSynthVersion){check(p.parameters.getRawParameterValue("mode_filt")->load()==static_cast<float>(monomachine::dspModeOld)&&p.parameters.getRawParameterValue("mode_dly")->load()==static_cast<float>(monomachine::dspModeOld),"legacy state must fall back to the old DSP, not to mnm");}p.parameters.replaceState(original);}
 std::cout<<"DSP1 SAW / NOISE / BBOX checks PASS\n";
}

int main(){juce::ScopedJuceInitialiser_GUI init;try{
    auto p=std::make_unique<P>();checkAmp(*p);checkFx142();allMachineSmoke();dsp1Checks(*p);
    check(p->getName()==(P::isSynthVersion?"Monomachine Nova Synth":"Monomachine Nova FX"),"plugin name");
    auto* level=p->parameters.getParameter("level");check(level->convertFrom0to1(1)==127&&level->convertFrom0to1(level->getDefaultValue())==100,"LEV range/default");
    check(p->parameters.getRawParameterValue("p0_5")->load()==64,"AMP VOL default");
    const auto waves=p->parameters.getParameter("p3_3")->getAllValueStrings();check(waves.joinIntoString(",")=="TRI,ITRI,SAW,ISAW,SQR,ISQR,EXP,IEXP,RMP,IRMP,RND","LFO order");
    check(p->parameters.getParameter("p3_0")->getAllValueStrings().joinIntoString(",")=="PTCH,SYNT,AMP,FILT,EFFX,LFO1,LFO2,LFO3","LFO pages");
    check(p->parameters.getParameter("r0_dest")->getAllValueStrings().size()==56,"matrix destination count");
    for(int i=0;i<10;i+=2)for(int t=0;t<100;++t)check(std::abs(nova::lfoShape(i,t/100.0)+nova::lfoShape(i+1,t/100.0))<1e-6,"LFO inverse");
    check(std::abs(nova::bipolarDist(0.1f,64.001f)-0.1f)<1e-5,"DIST discontinuity at zero");
    {monomachine::ModulationMatrix m;m.reset();for(size_t i=0;i<8;++i)m.configureRouting(i,false,monomachine::ModSource::LFO1,0,0);m.configureRouting(0,true,monomachine::ModSource::LFO1,55,16);m.setLfoOutputs(0.5f,0,0);std::array<float,56> a{},b{};a.fill(64.125f);m.evaluate(a,b);check(b[55]==72.125f&&b[0]==64.125f,"matrix LFO target or float precision");}
    {monomachine::MonomachineBBox box;check(box.getSlots().size()==24,"BBOX slot count");std::set<std::string> names;std::set<uint64_t> hashes;
        for(const auto& s:box.getSlots()){names.insert(s.name);uint64_t hash=14695981039346656037ull;for(float x:s.data){check(std::isfinite(x),"BBOX nonfinite");uint32_t word=0;std::memcpy(&word,&x,4);hash^=word;hash*=1099511628211ull;}hashes.insert(hash);}
        check(names.size()==24&&hashes.size()==24,"repeated default samples");
        check(box.chromaticSlot(48)==0&&box.chromaticSlot(60)==12&&box.chromaticSlot(72)==0,"BBOX chromatic layout");
        check(box.chromaticOctave(24)==-1&&box.chromaticOctave(72)==1,"BBOX transpose per 24 keys");
        const float ramp[]{0,0.1f,0.2f,0.3f,0.4f,0.5f,0.6f,0.7f};box.loadSample(0,"ramp",ramp,8);box.setParameters(64,0,0,0);box.setChromatic(true);float l[3]{},r[3]{};box.noteOn(48);box.processStereo(l,r,3);check(std::abs(l[1]-0.1f)<1e-6,"base sample pitch");box.noteOn(72);box.processStereo(l,r,3);check(std::abs(l[1]-0.2f)<1e-6,"upper repeated bank pitch");}
    {using A=monomachine::MonomachineArpeggiator;for(double bpm:{60.0,180.0}){A a;a.reset(48000,bpm);A::ArpSettings settings;settings.mode=A::Mode::Sid;settings.sync=false;settings.milliseconds=125;a.setSettings(settings);a.noteOn(60);a.noteOff(60);int count=0;for(int frame=0;frame<24000;++frame){for(int i=0;i<2;++i){auto e=a.poll();if(e.triggered&&!e.isNoteOff)++count;}a.advance(1);}check(count==4,"TIME rate depends on BPM or hold loses note");}}
    if(!P::isSynthVersion){set(*p,"level",100);set(*p,"fx_mix",0);p->prepareToPlay(48000,128);juce::AudioBuffer<float> b(2,128);for(int i=0;i<128;++i){b.setSample(0,i,0.1f);b.setSample(1,i,-0.1f);}juce::MidiBuffer midi;midi.addEvent(juce::MidiMessage::noteOn(1,60,static_cast<juce::uint8>(100)),17);midi.addEvent(juce::MidiMessage::noteOff(1,60),99);p->processBlock(b,midi);check(p->producesMidi()&&midi.getNumEvents()==2,"FX MIDI pass through");for(int i=0;i<128;++i)check(b.getSample(0,i)==0.1f&&b.getSample(1,i)==-0.1f,"global dry unity");}
    else{
        auto a=std::make_unique<P>(),b=std::make_unique<P>();for(P* x:{a.get(),b.get()}){set(*x,"p0_1",127);set(*x,"p4_0",0);set(*x,"p4_7",96);}set(*b,"p3_0",6);set(*b,"p3_1",5);set(*b,"p3_7",110);check(compareAudio(*a,*b)>0.01,"LFO1 to LFO2 speed not audible");
        a=std::make_unique<P>();b=std::make_unique<P>();for(P* x:{a.get(),b.get()})set(*x,"p0_1",127);set(*b,"r0_on",1);set(*b,"r0_src",2);set(*b,"macro_x",127);set(*b,"r0_dest",39);set(*b,"r0_depth",32);check(compareAudio(*a,*b)>0.01,"matrix to LFO1 depth not audible");
    }
    {auto state=p->parameters.copyState();state.setProperty("schema",3,nullptr);auto node=state.getChildWithProperty("id","level");node.setProperty("value",0.5f,nullptr);juce::MemoryBlock data;if(auto xml=state.createXml())P::copyXmlToBinary(*xml,data);p->setStateInformation(data.getData(),static_cast<int>(data.getSize()));p->flushSampleRestore();const auto v=p->parameters.getRawParameterValue("level")->load();check(v>=63&&v<=64,"old LEV migration");}
    {auto state=p->parameters.copyState();state.setProperty("schema",2,nullptr);state.getChildWithProperty("id","level").setProperty("value",80.0f,nullptr);state.getChildWithProperty("id","p3_3").setProperty("value",3,nullptr);juce::MemoryBlock data;if(auto xml=state.createXml())P::copyXmlToBinary(*xml,data);p->setStateInformation(data.getData(),static_cast<int>(data.getSize()));p->flushSampleRestore();check(p->parameters.getRawParameterValue("level")->load()==80,"schema2 raw LEV retained");check(p->parameters.getRawParameterValue("p3_3")->load()==4,"legacy PUL maps to SQR, not EXP");set(*p,"p3_3",0);}
    // Real GUI interaction: previously invisible matrix, scrollable settings and separate LFO tabs.
    set(*p,"level",100);set(*p,"p4_5",22);set(*p,"p5_5",111);std::unique_ptr<juce::AudioProcessorEditor> editor(p->createEditor());
    const juce::String prefix=P::isSynthVersion?"synth":"fx";saveImage(*editor,prefix+"-main.png");
    {auto* tempo=button(*editor,"120.0");check(tempo!=nullptr,"BPM button missing");const auto now=juce::Time::getCurrentTime();juce::MouseEvent e(juce::Desktop::getInstance().getMainMouseSource(),{5,5},juce::ModifierKeys(juce::ModifierKeys::leftButtonModifier),0,0,0,0,0,tempo,tempo,now,{5,5},now,2,false);tempo->mouseDoubleClick(e);auto* input=dynamic_cast<juce::TextEditor*>(named(*editor,"BPM entry"));check(input&&input->isVisible(),"BPM double click did not open editor");input->setText("137.5",false);input->onReturnKey();check(p->parameters.getRawParameterValue("bpm")->load()==137.5f&&p->parameters.getRawParameterValue("host_sync")->load()==0,"BPM edit/sync switch failed");
        auto* arp=button(*editor,"ARP");auto before=p->parameters.getRawParameterValue("arp_grid")->load();juce::MouseWheelDetails wheel;wheel.deltaY=0.1f;arp->mouseWheelMove(e,wheel);check(p->parameters.getRawParameterValue("arp_grid")->load()==before+1,"ARP wheel rate failed");check(!viewport(*editor)->isVisible(),"ARP wheel opened settings");}
    auto* amp=button(*editor,"AMP");check(amp&&amp->onClick,"AMP header button");amp->onClick();auto* ampView=viewport(*editor);check(ampView&&ampView->isVisible()&&ampView->getViewedComponent()->getHeight()>400,"AMP editor not visible");saveImage(*editor,prefix+"-amp.png");button(*editor,"BACK")->onClick();
    {auto* knob=ampDecaySlider(*editor);check(knob!=nullptr,"AMP DEC knob");const auto value=knob->getValue();const auto now=juce::Time::getCurrentTime();juce::MouseEvent right(juce::Desktop::getInstance().getMainMouseSource(),{5,5},juce::ModifierKeys(juce::ModifierKeys::rightButtonModifier),0,0,0,0,0,knob,knob,now,{5,5},now,1,false);knob->mouseDown(right);knob->mouseUp(right);check(viewport(*editor)->isVisible(),"right click AMP curve editor");check(knob->getValue()==value,"right click modified decay time");button(*editor,"BACK")->onClick();}
    auto* matrix=button(*editor,"MATRIX");check(matrix&&matrix->onClick,"matrix button");matrix->onClick();auto* view=viewport(*editor);check(view&&view->isVisible()&&view->getViewedComponent()&&view->getViewedComponent()->getWidth()>1000&&view->getViewedComponent()->getHeight()>300,"matrix not visible/sized");saveImage(*editor,prefix+"-matrix.png");
    auto* arp=button(*editor,"ARP");check(arp&&arp->onClick,"arp button");arp->onClick();check(view->getViewedComponent()->getHeight()>430,"settings cannot scroll");saveImage(*editor,prefix+"-arp.png");
    auto* back=button(*editor,"BACK");check(back&&back->onClick,"back button");back->onClick();check(!view->isVisible(),"back does not close overlay");
    auto* tab=button(*editor,"LFO3");check(tab&&tab->onClick,"LFO3 tab");tab->onClick();auto* speed=lfoSpeed(*editor);check(speed&&speed->getValue()==111,"LFO3 tab bound to wrong page");tab=button(*editor,"LFO2");check(tab&&tab->onClick,"LFO2 tab");tab->onClick();speed=lfoSpeed(*editor);check(speed&&speed->getValue()==22,"LFO2 tab bound to wrong page");
    if(P::isSynthVersion){editor.reset();int bbox=0;for(size_t i=0;i<nova::machines().size();++i)if(nova::machines()[i].id==7)bbox=static_cast<int>(i);set(*p,"machine",static_cast<float>(bbox));set(*p,"m7_2",0);editor.reset(p->createEditor());
        const auto file=juce::File::getCurrentWorkingDirectory().getChildFile("test-drop.wav");{auto stream=file.createOutputStream();juce::WavAudioFormat format;std::unique_ptr<juce::AudioFormatWriter> writer(format.createWriterFor(stream.release(),44100,1,16,{},0));check(writer!=nullptr,"test WAV");juce::AudioBuffer<float> wave(1,512);for(int i=0;i<512;++i)wave.setSample(0,i,0.2f*std::sin(i*0.1f));check(writer->writeFromAudioSampleBuffer(wave,0,512),"test WAV write");}
        juce::StringArray files{file.getFullPathName(),file.getFullPathName()};auto* drop=dropTarget(*editor,files);check(drop!=nullptr,"no BBOX slot drop target");drop->filesDropped(files,0,0);check(p->sampleName(0)=="test-drop.wav"&&p->sampleName(1)=="test-drop.wav","multi-file slot import");file.deleteFile();juce::MemoryBlock data;p->getStateInformation(data);auto restored=std::make_unique<P>();restored->setStateInformation(data.getData(),static_cast<int>(data.getSize()));restored->flushSampleRestore();check(restored->sampleName(1)=="test-drop.wav","24-slot state import roundtrip");saveImage(*editor,"synth-bbox.png");
        auto* cell=dynamic_cast<juce::Component*>(drop);check(cell!=nullptr,"slot component");
        const auto now=juce::Time::getCurrentTime();juce::MouseEvent right(juce::Desktop::getInstance().getMainMouseSource(),{5,5},juce::ModifierKeys(juce::ModifierKeys::rightButtonModifier),0,0,0,0,0,cell,cell,now,{5,5},now,1,false);
        cell->mouseDown(right);cell->mouseUp(right);auto* browser=viewport(*editor);check(browser&&browser->isVisible()&&browser->getViewedComponent(),"BBOX right click browser");auto* restoreKit=button(*editor,"RESTORE KIT");check(restoreKit&&restoreKit->onClick,"restore kit button missing");restoreKit->onClick();check(p->sampleName(0)!="test-drop.wav"&&p->sampleName(1)!="test-drop.wav","restore kit did not replace imported samples");auto* oldKit=button(*editor,"OLD KIT");check(oldKit&&oldKit->onClick,"old kit button missing");oldKit->onClick();juce::MemoryBlock oldData;p->getStateInformation(oldData);auto oldXml=P::getXmlFromBinary(oldData.getData(),static_cast<int>(oldData.getSize()));check(oldXml!=nullptr,"old kit state XML");check(juce::ValueTree::fromXml(*oldXml).getChildWithName("Samples").getNumChildren()==24,"old kit not embedded in state");restoreKit->onClick();saveImage(*editor,"synth-samples.png");
    }
    std::cout<<(P::isSynthVersion?"Synth":"FX")<<": 1.4 host params, DSP, ARP, MIDI, BBOX, state, GUI tests PASS\n";return 0;
}catch(const std::exception& e){std::cerr<<"FAIL: "<<e.what()<<'\n';return 1;}}
