#!/usr/bin/env python3
"""exp25f_genvecs.py — generate C++ test vectors for mnm_phaser.h:
   tables (sin/cos 8192 words) + N blocks of (params, input, expected output)
   straight from the emulator. Writes 18_m18_final/test_vectors.h"""
import sys, random, math

sys.path.insert(0, "/home/z/my-project/scripts")
from exp25_verify import build, run_init, run_emu_block, R6M, M24  # noqa
from exp25_model import M18State  # noqa

OUT = ("/home/z/my-project/download/mmnova/decompiled data/09_not_sorted/"
       "missing_data/filter_phaser_pack/18_m18_final/test_vectors.h")


def main():
    random.seed(99)
    e = build()
    run_init(e)
    ts = [e.X.get(0x14A000 + i, 0) for i in range(8192)]
    tc = [e.X.get(0x14A800 + i, 0) for i in range(8192)]

    cases = []
    # deterministic cases
    cases.append(([64, 64, 0, 64, 64, 64, 64, 100], "impulse", 6))
    cases.append(([96, 127, 64, 127, 96, 100, 0, 127], "sine", 6))
    cases.append(([32, 20, 8, 0, 32, 30, 127, 60], "dc", 6))
    # random cases (param changes mid-stream to exercise state carry)
    for c in range(3):
        cases.append(([random.randint(0, 127) for _ in range(8)], "rand", 8))

    blocks = []
    for pv, kind, n in cases:
        e2 = build()
        run_init(e2)
        for blk in range(n):
            reset = (blk == 0)
            if kind == "impulse":
                sg = [0x400000] + [0] * 33
            elif kind == "dc":
                sg = [0x200000] * 34
            elif kind == "sine":
                sg = [int(0x600000 * math.sin(0.9 * i)) & M24 for i in range(34)]
            else:
                sg = [random.randint(-0x700000, 0x700000) & M24 for _ in range(34)]
            eout = run_emu_block(e2, pv, sg)
            blocks.append((pv, sg, eout, reset))

    with open(OUT, "w") as f:
        f.write("// generated by exp25f_genvecs.py — emulator reference vectors\n")
        f.write("#pragma once\n#include <cstdint>\nnamespace mnmtest {\n")
        f.write("static const int32_t kSinTab[8192] = {")
        f.write(",".join(str(v if v < 0x800000 else v - (1 << 24)) for v in ts))
        f.write("};\nstatic const int32_t kCosTab[8192] = {")
        f.write(",".join(str(v if v < 0x800000 else v - (1 << 24)) for v in tc))
        f.write("};\n")
        f.write("struct Block { int32_t prm[8]; int32_t in[34]; int32_t out[32]; bool reset; };\n")
        f.write("static const Block kBlocks[] = {\n")
        for pv, sg, eout, reset in blocks:
            f.write("{{%s},{%s},{%s},%s},\n" % (
                ",".join(str((v & 0xFFFF) << 16) for v in pv),
                ",".join(str(v if v < 0x800000 else v - (1 << 24)) for v in sg),
                ",".join(str(v if v < 0x800000 else v - (1 << 24)) for v in eout),
                "true" if reset else "false"))
        f.write("};\nstatic const int kNumBlocks = %d;\n} // namespace\n" % len(blocks))
    print("wrote %s: %d blocks" % (OUT, len(blocks)))


if __name__ == "__main__":
    main()
