#include "PluginProcessor.h"
#include "PluginEditor.h"
#include "PatchSettings.h"
#include <iostream>
#include <stdexcept>
#include <map>
#include <set>
void require(bool b,const char* text){if(!b)throw std::runtime_error(text);}
float get(MonoJuiceAudioProcessor& p,const juce::String& id){auto* v=p.parameters.getRawParameterValue(id);require(v!=nullptr,"missing registered parameter");return v->load();}
void set(MonoJuiceAudioProcessor& p,int slot,const char* key,float v){p.setValue(model::id(slot,key),v);}
std::map<juce::String,float> values(MonoJuiceAudioProcessor& p){std::map<juce::String,float> result;for(auto n:p.parameters.copyState())result[n["id"].toString()]=get(p,n["id"].toString());return result;}
void importState(MonoJuiceAudioProcessor& p,const juce::String& root,std::initializer_list<std::pair<const char*,float>> entries){juce::ValueTree t(root);for(auto v:entries){juce::ValueTree n("PARAM");n.setProperty("id",v.first,nullptr);n.setProperty("value",v.second,nullptr);t.addChild(n,-1,nullptr);}juce::MemoryBlock data;juce::AudioProcessor::copyXmlToBinary(*t.createXml(),data);p.setStateInformation(data.getData(),int(data.getSize()));}
int main(int argc,char** argv){try{
 juce::ScopedJuceInitialiser_GUI init;MonoJuiceAudioProcessor p,other;require(p.getName()=="MonoJuice"&&p.getParameters().size()==739,"739 registered MonoJuice parameters");require(!p.settings().slots[0].spectralExtended&&p.settings().clipper&&p.settings().dcBlock,"new defaults: classic and output protection");
 for(auto* parameter:p.getParameters())parameter->setValueNotifyingHost(.37f);p.selectedSlot=4;juce::MemoryBlock state;p.getStateInformation(state);other.setStateInformation(state.getData(),int(state.getSize()));require(values(p)==values(other)&&other.selectedSlot==4,"full state roundtrip");
 auto before=values(p);p.swapSlots(0,4);for(auto spec:model::params)require(get(p,model::id(0,spec.id))==before[model::id(4,spec.id)]&&get(p,model::id(4,spec.id))==before[model::id(0,spec.id)],"numeric bank move");for(auto key:model::slotKeys)require(get(p,model::id(0,key))==before[model::id(4,key)],"choice bank move");require(get(p,"MASTER_FB")==before["MASTER_FB"],"move doesn't change master");
 importState(other,"NOVA_FX5_STATE",{{"S1_TYPE",4},{"S1_K_FREQ_A",880},{"S1_K_RES_A",91},{"S1_K_ROUTING",2},{"S4_TYPE",5},{"S4_S_PROM",27}});require(get(other,"S1_K_MODEL")==0&&get(other,"S1_K_FREQ_A")==880&&get(other,"S1_K_ROUTING")==2&&get(other,"S1_K_DRIVE")==0&&get(other,"S1_K_OUT")==0&&get(other,"S4_S_MODE")==0&&get(other,"OUT_CLIP")==0&&get(other,"OUT_DC")==0,"0.5 ODIN restored and neutral output migration");
 importState(other,"NOVA_FX5_STATE",{{"S1_TYPE",4},{"S1_K_T1",100},{"S1_K_DRY_DB",0},{"S4_TYPE",5},{"S4_S_SHIFT",7}});require(get(other,"S1_K_MODEL")==1&&get(other,"S1_K_T1")==100&&get(other,"S1_K_DRIVE")==0&&get(other,"S4_S_MODE")==1&&get(other,"S4_S_SHIFT")==7,"0.6/0.7 Parallel and nonneutral extended migration");
 importState(other,"NOVA_CHORUS_STATE",{{"DEL",83}});require(other.settings().slots[1].chorus[0]==83&&other.settings().slots[1].on,"chorus legacy");importState(other,"NOVA_FX3_STATE",{{"DEL",73},{"P_SHIFT",7},{"P_ON",1},{"C_ON",0},{"G_FEEDBACK",97}});require(other.settings().slots[0].pitch.semitones==7&&!other.settings().slots[1].on&&other.settings().slots[2].grain.feedback==97,"FX3 legacy");before=values(other);other.setStateInformation("bad",3);require(values(other)==before,"malformed state ignored");
 auto checkPatch=[&](int slot,const factory::Patch& patch,const std::map<juce::String,float>& old){auto expected=old;for(auto v:patch){auto id=model::id(slot,v.first);auto* param=p.parameters.getParameter(id);require(param!=nullptr,"factory parameter exists");expected[id]=param->convertFrom0to1(param->convertTo0to1(v.second));}for(auto v:values(p))require(std::abs(v.second-expected[v.first])<=std::max(.0001f,std::abs(expected[v.first])*.000001f),"patch values and bank isolation");};
 for(int slot=0;slot<5;slot++)for(int type:{4,5})for(int n=0;n<10;n++){set(p,slot,"TYPE",float(type));before=values(p);require(p.applyFactoryPreset(slot,n),"load factory");checkPatch(slot,factory::preset(type,n),before);require(p.matchingFactoryPreset(slot)==n,"factory label");juce::MemoryBlock b;p.getStateInformation(b);other.setStateInformation(b.getData(),int(b.getSize()));require(values(p)==values(other)&&other.matchingFactoryPreset(slot)==n,"factory state and label");}
 for(int slot=0;slot<5;slot++)for(int type=1;type<=5;type++)for(int v=0;v<(type>=4?2:1);v++){set(p,slot,"TYPE",float(type));if(type>=4)set(p,slot,type==4?"K_MODEL":"S_MODE",float(v));before=values(p);p.randomiseSlot(slot,1234);checkPatch(slot,factory::randomize(type,1234,v),before);require(values(p)!=before,"random changes values");auto first=values(p);p.randomiseSlot(slot,1234);require(values(p)==first,"fixed seed reproducibility");}
 set(p,0,"TYPE",4);set(p,0,"K_MODEL",1);before=values(p);p.initialiseSlot(0);require(get(p,"S1_K_MODEL")==1&&get(p,"S1_K_FREQ_A")==before["S1_K_FREQ_A"]&&p.matchingFactoryPreset(0)==5,"INIT preserves other COMB bank");before=values(p);p.panicComb(0);require(get(p,"S1_K_FB")==0&&get(p,"S1_K_RES_A")==0&&get(p,"S2_K_FB")==before["S2_K_FB"],"local PANIC isolation");before=values(p);p.panicAll();require(get(p,"MASTER_FB")==0&&get(p,"S2_K_FB")==before["S2_K_FB"]&&get(p,"OUT_DC")==before["OUT_DC"],"master PANIC scope");
 std::cout<<"739 STATE / BOTH MODELS MIGRATION / ALL BANKS MOVE / 100 PRESETS / 35 RANDOM SLOT-VARIANTS / INIT / PANIC PASS\n";
 // Real processor audio for the new banks and output loop, including variable blocks.
 for(int i=0;i<5;i++){set(p,i,"TYPE",0);set(p,i,"ON",0);}p.setValue("BYPASS",0);p.setValue("OUT_CLIP",1);p.setValue("OUT_DC",1);p.setValue("MASTER_FB",35);
 for(double sr:{44100.,48000.,96000.}){p.setRateAndBufferSizeDetails(sr,1024);p.prepareToPlay(sr,1024);for(int type:{4,5})for(int n=0;n<10;n++){set(p,0,"TYPE",float(type));set(p,0,"ON",1);p.applyFactoryPreset(0,n);double energy=0;int at=0,j=0;const int sizes[]={1,7,63,127,512,1024};while(at<int(sr)){const int count=std::min(sizes[j++%6],int(sr)-at);juce::AudioBuffer<float> b(2,count);juce::MidiBuffer m;for(int i=0;i<count;i++){auto x=testInput(at+i,int(sr));b.setSample(0,i,x.l);b.setSample(1,i,x.r);}p.processBlock(b,m);for(int c=0;c<2;c++)for(int i=0;i<count;i++){const float v=b.getSample(c,i);require(std::isfinite(v)&&std::abs(v)<=1,"real processor clipper / audio");energy+=v*v;}at+=count;}require(energy>1e-8,"real processor non-silent");}std::cout<<"20 PRESETS + MASTER LOOP + DC/CLIP VARIABLE BLOCKS @ "<<sr<<" PASS\n";}
 MonoJuiceAudioProcessor::BusesLayout mono;mono.inputBuses.add(juce::AudioChannelSet::mono());mono.outputBuses.add(juce::AudioChannelSet::mono());require(other.setBusesLayout(mono),"mono supported");other.setRateAndBufferSizeDetails(48000,128);other.prepareToPlay(48000,128);juce::AudioBuffer<float> mb(1,128);mb.clear();juce::MidiBuffer midi;other.processBlock(mb,midi);
 auto editor=std::unique_ptr<MonoJuiceAudioProcessorEditor>(static_cast<MonoJuiceAudioProcessorEditor*>(p.createEditor()));std::set<juce::String> bound;int loads=0;
 juce::ComboBox* factoryMenu=nullptr;juce::TextButton* random=nullptr;
 for(auto* c:editor->getChildren()){if(c->getName()=="FACTORY_PRESET")factoryMenu=dynamic_cast<juce::ComboBox*>(c);if(c->getName()=="RANDOM")random=dynamic_cast<juce::TextButton*>(c);}
 require(factoryMenu&&random&&factoryMenu->getNumItems()==10,"factory GUI exists");
 for(int slot=0;slot<5;slot++)for(int type=1;type<=5;type++)for(int variant=0;variant<(type>=4?2:1);variant++){
  set(p,slot,"TYPE",float(type));if(type>=4)set(p,slot,type==4?"K_MODEL":"S_MODE",float(variant));editor->showSlot(slot);
  const int pages=type==1||type==2?2:(type==3?3:(type==4?(variant?6:4):(variant?3:2)));
  for(int page=0;page<pages;page++){editor->showPage(page);for(auto* c:editor->getChildren())if(auto* slider=dynamic_cast<juce::Slider*>(c))if(slider->isVisible()){require(slider->getBounds().getBottom()<=editor->getHeight(),"slider bounds");auto id=slider->getName();const double old=slider->getValue();slider->setValue(slider->getMinimum(),juce::sendNotificationSync);require(std::abs(get(p,id)-float(slider->getMinimum()))<.0001f,"slider APVTS binding");slider->setValue(old,juce::sendNotificationSync);bound.insert(id);}}
  if(type>=4&&variant==0)for(int n=0;n<10;n++){factoryMenu->setSelectedId(0,juce::dontSendNotification);factoryMenu->setSelectedId(n+1,juce::sendNotificationSync);require(p.matchingFactoryPreset(slot)==n,"preset menu loads DSP params");++loads;}
  auto old=values(p);random->onClick();require(values(p)!=old,"GUI RANDOM live");
 }
 require(bound.size()==671&&loads==100,"670 per-slot numeric controls plus master bound / 100 menu selections");
 for(auto* c:editor->getChildren())if(auto* button=dynamic_cast<juce::ToggleButton*>(c)){auto id=button->getName();bool old=button->getToggleState();button->setToggleState(!old,juce::sendNotificationSync);require(get(p,id)==float(!old),"output checkbox binding");button->setToggleState(old,juce::sendNotificationSync);}
 set(p,0,"TYPE",0);editor->showSlot(0);require(!random->isEnabled(),"EMPTY RANDOM disabled");
 std::cout<<"671 SLIDER BINDINGS / 100 MENU LOADS / RANDOM / OUTPUT CHECKBOXES PASS\n";
 const int order[]={4,1,2,5,3};p.setValue("MASTER_FB",0);p.setValue("OUT_CLIP",1);p.setValue("OUT_DC",1);for(int i=0;i<5;i++){set(p,i,"TYPE",float(order[i]));set(p,i,"ON",1);p.initialiseSlot(i);}p.applyFactoryPreset(0,0);p.applyFactoryPreset(3,0);editor->showSlot(0);
 auto folder=argc>1?juce::File::getCurrentWorkingDirectory().getChildFile(argv[1]):juce::File{};if(argc>1)folder.createDirectory();std::exception_ptr error;
 auto shot=[&](const char* name){if(argc<=1)return;auto image=editor->createComponentSnapshot(editor->getLocalBounds());require(image.getPixelAt(2,2)==theme::bg&&image.getWidth()==960&&image.getHeight()==860,"dark full GUI");auto f=folder.getChildFile(juce::String(name)+".png");f.deleteFile();auto out=f.createOutputStream();juce::PNGImageFormat png;require(out&&png.writeImageToStream(image,*out),"PNG export");};
 juce::Timer::callAfterDelay(160,[&]{try{require(p.getLatencySamples()==139+4096,"idle model/window PDC");for(int i=0;i<5;i++){editor->showSlot(i);shot(model::typeNames[order[i]]);}editor->showSlot(0);editor->showPage(1);shot("ODIN_MOTION");p.applyFactoryPreset(0,5);editor->showSlot(0);shot("PARALLEL");editor->showPage(1);shot("PARALLEL_ADVANCED");editor->showPage(2);shot("PARALLEL_MOTION");set(p,3,"S_MODE",1);editor->showSlot(3);shot("SPECTRE_EXTENDED");}catch(...){error=std::current_exception();}juce::MessageManager::getInstance()->stopDispatchLoop();});juce::MessageManager::getInstance()->runDispatchLoop();if(error)std::rethrow_exception(error);
 std::cout<<"MONOJUICE 0.8 JUCE WRAPPER ALL PASS\n";return 0;
}catch(const std::exception& e){std::cerr<<"FAIL "<<e.what()<<'\n';return 1;}}
