#!/usr/bin/env python3
"""Generate MnmTables.hpp from the extracted Monomachine OS1.32B DSP1 image.

All values are taken 1:1 from the firmware image (no rounding to "nice" numbers):
  P:$141800  attack/ramp rate table        (128 words, per 16-sample block)
  P:$141880  decay/release rate table      (128 words, magnitudes)
  P:$144AC7  TONE/LP one-pole coefficient  (bank A = words 0..127, bank B = words 129..256)
  P:$141A80  FM operator ratio table       (24 words, ratio = raw / 0x80000)
  P:$144C49  delay-time reciprocal table   (64 words, 1/(n+1))
"""
import sys

IMAGE = "dsp1_pmem_full.bin"
OUT = sys.argv[1] if len(sys.argv) > 1 else "MnmTables.hpp"


def load(p):
    b = open(p, "rb").read()
    return [int.from_bytes(b[i * 3:i * 3 + 3], 'big') for i in range(len(b) // 3)]


P = load(IMAGE)


def s24(v):
    return v - 0x1000000 if v >= 0x800000 else v


def frac(v):
    return s24(v) / 8388608.0


def fmt(vals, per=6, digits=9):
    out = []
    for i in range(0, len(vals), per):
        out.append("        " + ", ".join(f"{v:.{digits}f}f" for v in vals[i:i + per]) + ",")
    return "\n".join(out)


attack = [frac(P[0x141800 + i]) for i in range(128)]
decay = [abs(frac(P[0x141880 + i])) for i in range(128)]
lp_a = [frac(P[0x144AC7 + i]) for i in range(128)]
lp_b = [frac(P[0x144AC7 + 129 + i]) for i in range(128)]
ratio = [P[0x141A80 + i] / float(0x80000) for i in range(24)]
delay_rec = [P[0x144C49 + i] / float(0x800000) for i in range(64)]

header = f"""// AUTO-GENERATED by tools/gen_tables.py from the Monomachine OS 1.32B DSP1 image.
// Source of truth: P-memory image dsp1_pmem_full.bin (independently re-extracted from
// elektron_sfx6-60_os1.32b.bin, 0 mismatches against the pack image), 24-bit big-endian words.
// Do not hand-edit: regenerate with tools/gen_tables.py <path-to-image> MnmTables.hpp
#pragma once
#include <array>
#include <cstdint>

namespace monomachine {{ namespace mnm {{

// P:$141800 -- attack / attack-ramp rate table. Value is added to the 0..1 envelope
// accumulator once per 16-sample DSP block. Index = ATK parameter (0..127).
// idx 0 = 0.5 (instant), idx 127 = 1.20e-05 (~30 s ramp).
inline constexpr std::array<float,128> kEnvAttackRate = {{
{fmt(attack)}
}};

// P:$141880 -- decay / release rate table. Magnitudes of the per-16-sample-block
// multipliers. The firmware stores the negatives (0x8D1897 ... 0x800000) and applies them
// as `mpy -x1,y0,a`, i.e. level = level * |table[i]|. Index = DEC / REL parameter.
// idx 0 = 0.897687 (-1.06 dB per block), idx 64 = 0.9985473 -> -34.80 dB/s at 44.1 kHz
// (the shipped reference measurement for AMP DEC=64 is -34.888 dB/s, 0.25 % apart).
inline constexpr std::array<float,128> kEnvDecayRate = {{
{fmt(decay)}
}};

// P:$144AC7 bank A -- one-pole low-pass coefficient c for y += c*(x-y).
// Coefficient of the shared TONE / LP filter used by FM TONE, CHORUS LP and REV LP.
// idx 0 -> c=0.002211 (~15.5 Hz @44.1 kHz), idx 127 -> c=0.91201 (~17.1 kHz).
inline constexpr std::array<float,128> kLpCoeffA = {{
{fmt(lp_a)}
}};

// P:$144AC7 bank B (base + 129) -- second coefficient bank of the same table.
inline constexpr std::array<float,128> kLpCoeffB = {{
{fmt(lp_b)}
}};

// P:$141A80 -- FM operator ratio table, 24 entries. Firmware index is
//   n = ((param + 0x8000) * 24) >> 24   (param = 24-bit knob word, 0..0x7FFFFF)
// and the ratio is raw / 0x80000 (1/32 ... 8).
inline constexpr std::array<float,24> kFmRatio = {{
{fmt(ratio, 6)}
}};

// P:$144C49 -- delay-time reciprocal table, 1/(n+1). The FX-DLY machine multiplies the
// DEL parameter by this table to obtain the read-pointer rate.
inline constexpr std::array<float,64> kDelayRecip = {{
{fmt(delay_rec, 6)}
}};

}} // namespace mnm
}} // namespace monomachine
"""

open(OUT, "w").write(header)
print("wrote", OUT, len(header), "bytes")
print("attack[64]", attack[64], "decay[64]", decay[64], "lpA[64]", lp_a[64])
