#include "PluginEditor.h"
namespace {
class PixelLabel final:public juce::Label {void paint(juce::Graphics& g)override{g.fillAll(theme::bg);if(!isBeingEdited()){g.setColour(isEnabled()?theme::ink:theme::dim);pixel::text(g,getText(),getLocalBounds(),14,true);}}};
juce::Label* makeLabel(){auto* l=new PixelLabel();l->setJustificationType(juce::Justification::centred);l->setColour(juce::TextEditor::textColourId,theme::ink);l->setColour(juce::TextEditor::backgroundColourId,theme::bg);l->setColour(juce::TextEditor::outlineColourId,theme::ink);return l;}
// Highest page index per effect. LFO pages always come AFTER the base pages,
// so existing page indices (and GUI screenshots) keep their meaning.
int lastPage(int type,int variant){if(type==1)return 1;if(type==2)return 1;if(type==3)return 2;if(type==4)return variant?5:3;if(type==5)return variant?2:1;return 0;}
}
RackLookAndFeel::RackLookAndFeel(){setColour(juce::PopupMenu::backgroundColourId,theme::panel);setColour(juce::PopupMenu::textColourId,theme::ink);setColour(juce::PopupMenu::highlightedBackgroundColourId,theme::ink);setColour(juce::PopupMenu::highlightedTextColourId,theme::bg);setColour(juce::TooltipWindow::backgroundColourId,theme::panel);setColour(juce::TooltipWindow::textColourId,theme::ink);setColour(juce::TooltipWindow::outlineColourId,theme::dim);}
juce::Label* RackLookAndFeel::createSliderTextBox(juce::Slider&){auto* l=makeLabel();l->setKeyboardType(juce::TextInputTarget::decimalKeyboard);return l;}
juce::Label* RackLookAndFeel::createComboBoxTextBox(juce::ComboBox&){return makeLabel();}
void RackLookAndFeel::positionComboBoxText(juce::ComboBox& b,juce::Label& l){l.setBounds(4,2,b.getWidth()-28,b.getHeight()-4);}
void RackLookAndFeel::drawComboBox(juce::Graphics& g,int w,int h,bool,int,int,int,int,juce::ComboBox& b){g.fillAll(theme::bg);g.setColour(b.isEnabled()?theme::ink:theme::dim);g.drawRect(0,0,w,h,2);for(int i=0;i<4;i++)g.fillRect(w-20+i,h/2-2+i,9-i*2,1);}
void RackLookAndFeel::drawRotarySlider(juce::Graphics& g,int x,int y,int w,int h,float position,float start,float end,juce::Slider& s){const int cx=x+w/2,cy=y+h/2;const float r=float(std::min(w,h))/2-8;g.setColour(s.isEnabled()?theme::ink:theme::dim);
 for(int i=0;i<72;i++){const float a=juce::MathConstants<float>::twoPi*i/72;const int px=int(std::round(cx+std::sin(a)*r)),py=int(std::round(cy-std::cos(a)*r));g.fillRect((px/2)*2,(py/2)*2,3,3);}
 const float a=start+position*(end-start);for(int d=5;d<int(r)-3;d+=2){const int px=int(std::round(cx+std::sin(a)*d)),py=int(std::round(cy-std::cos(a)*d));g.fillRect((px/2)*2,(py/2)*2,3,3);}if(s.isMouseOverOrDragging())g.drawRect(x+2,y+2,w-4,h-4);
}
void RackLookAndFeel::drawButtonBackground(juce::Graphics& g,juce::Button& b,const juce::Colour&,bool hover,bool down){const bool fill=b.getToggleState()||down;g.fillAll(fill?theme::ink:theme::bg);g.setColour(b.isEnabled()?theme::ink:theme::dim);g.drawRect(b.getLocalBounds(),hover?3:2);}
void RackLookAndFeel::drawToggleButton(juce::Graphics& g,juce::ToggleButton& b,bool,bool){g.fillAll(theme::bg);g.setColour(theme::ink);g.drawRect(2,5,20,20,2);if(b.getToggleState()){g.drawLine(6,15,11,20,3);g.drawLine(11,20,19,9,3);}pixel::text(g,b.getButtonText(),{30,0,b.getWidth()-30,b.getHeight()},14);}
void RackLookAndFeel::drawButtonText(juce::Graphics& g,juce::TextButton& b,bool,bool down){g.setColour(!b.isEnabled()?theme::dim:(b.getToggleState()||down?theme::bg:theme::ink));pixel::text(g,b.getButtonText(),b.getLocalBounds(),14,true);}
MonoJuiceAudioProcessorEditor::MonoJuiceAudioProcessorEditor(MonoJuiceAudioProcessor& p):AudioProcessorEditor(&p),processor(p){setLookAndFeel(&look);
 for(int i=0;i<model::count;i++){auto& s=sliders[i];const auto& spec=model::params[i];addAndMakeVisible(s);s.setSliderStyle(juce::Slider::RotaryHorizontalVerticalDrag);s.setTextBoxStyle(juce::Slider::TextBoxBelow,false,104,24);s.setRange(spec.min,spec.max,spec.step);s.setDoubleClickReturnValue(true,spec.initial);s.setRotaryParameters(juce::MathConstants<float>::pi*1.25f,juce::MathConstants<float>::pi*2.75f,true);s.setTooltip(juce::String(spec.name)+" ["+spec.unit+"]. Double-click: default.");}
 for(int i=0;i<5;i++){addAndMakeVisible(tabs[i]);tabs[i].setName("SELECT_"+juce::String(i+1));tabs[i].setButtonText("SLOT 0"+juce::String(i+1));tabs[i].onClick=[this,i]{showSlot(i);};addAndMakeVisible(enabled[i]);enabled[i].setName(model::id(i,"ON"));enabled[i].setButtonText("ON");enabled[i].setClickingTogglesState(true);enableAttachments[i]=std::make_unique<ButtonAttachment>(p.parameters,model::id(i,"ON"),enabled[i]);
  addAndMakeVisible(types[i]);types[i].setName(model::id(i,"TYPE"));for(int j=0;j<6;j++)types[i].addItem(model::typeNames[j],j+1);types[i].setTooltip("Choose this slot's effect. Repeats are allowed. Click SLOT to edit; MOVE keeps its settings. Type changes clear audio memory and update latency.");typeAttachments[i]=std::make_unique<ComboAttachment>(p.parameters,model::id(i,"TYPE"),types[i]);types[i].onChange=[this,i]{if(i==selected&&type!=types[i].getSelectedItemIndex())showSlot(i);else repaint();};
 }
 for(auto* b:{&negativeA,&negativeB,&init,&clear,&freeze,&metalPreset,&bypass,&moveLeft,&moveRight,&midSide,&oversample,&spectralFreeze,&panic,&previousPage,&nextPage,&randomise})addAndMakeVisible(*b);
 randomise.setName("RANDOM");randomise.setTooltip("Randomize only the selected FX bank. Keeps type/order, ON, bypass and other slots. Clears this FX history; Freeze and COMB 16x are off. Levels are constrained, not guaranteed clip-free.");
 randomise.onClick=[this]{processor.randomiseSlot(selected,uint32_t(randomSource.nextInt()));refreshPreset();};
 addAndMakeVisible(presetMenu);presetMenu.setName("FACTORY_PRESET");presetMenu.setTextWhenNothingSelected("CUSTOM");for(int n=1;n<=10;n++)presetMenu.addItem("Preset "+juce::String(n),n);
 presetMenu.onChange=[this]{if(presetMenu.getSelectedId()>0)processor.applyFactoryPreset(selected,presetMenu.getSelectedId()-1);refreshPreset();};
 init.onClick=[this]{processor.initialiseSlot(selected);};clear.onClick=[this]{processor.clearSlot(selected);};metalPreset.onClick=[this]{processor.metalCloudPreset(selected);};moveLeft.onClick=[this]{processor.swapSlots(selected,selected-1);showSlot(processor.selectedSlot.load());};moveRight.onClick=[this]{processor.swapSlots(selected,selected+1);showSlot(processor.selectedSlot.load());};
 for(auto* b:{&freeze,&bypass,&midSide,&oversample,&spectralFreeze})b->setClickingTogglesState(true);bypassAttachment=std::make_unique<ButtonAttachment>(p.parameters,"BYPASS",bypass);
 addAndMakeVisible(spectreWindow);for(int i=0;i<8;i++)spectreWindow.addItem(juce::String(model::windowNames[i])+" SMP",i+1);
 midSide.setTooltip("ParallelComb channel processing: OFF = left/right, ON = mid/side.");oversample.setTooltip("Original ParallelComb 16x oversampling. Mode changes clear this slot's comb memory. Higher CPU cost.");panic.setTooltip("Set this slot's feedback to zero and clear its memory.");panic.onClick=[this]{processor.panicComb(selected);};previousPage.onClick=[this]{showPage(page-1);};nextPage.onClick=[this]{showPage(page+1);};
 spectralFreeze.setTooltip("Hold the last two MDCT coefficient frames and extrapolate their quarter-cycle phase. Capture input first. Dry remains live; capture is not saved in state.");spectreWindow.setTooltip("MDCT window. Changing it clears this slot and updates latency. Prefer stopped transport.");freeze.setTooltip("Hold only this slot's granular recording.");
 init.setTooltip("Reset only this slot's selected effect parameters and audio memory.");clear.setTooltip("Clear only this slot's selected effect memory, keeping parameters.");moveLeft.setTooltip("Swap this slot and the previous one, including all settings. Audio histories are cleared.");moveRight.setTooltip("Swap this slot and the next one, including all settings. Audio histories are cleared.");
 for(auto* b:{&negativeA,&negativeB})b->setClickingTogglesState(true);
 addAndMakeVisible(modelMenu);modelMenu.onChange=[this]{const auto s=processor.settings().slots[selected];const int v=type==4?s.colour.model:(s.spectralExtended?1:0);if(v!=variant){variant=v;showPage(0);}};
 addAndMakeVisible(odinRouting);odinRouting.onChange=[this]{showPage(page);};odinRouting.addItem("A ONLY",1);odinRouting.addItem("A > B",2);odinRouting.addItem("A + B",3);
 addAndMakeVisible(chorusMode);chorusMode.addItem("V1",1);chorusMode.addItem("V2",2);chorusMode.setTooltip("Chorus core mode. V1 = original internal mix (pre-fix sound, default). V2 = fixed external mix: MIX 0 is bit-clean input at any INP.");
 sliders[130].setTooltip("LFO / Rate. Free-run speed in Hz while SYNC is off. Bipolar modulator, one per slot.");sliders[131].setTooltip("LFO / Shape. 0 SINE, 1 TRI, 2 SQUARE, 3 SAW, 4 SAMPLE&HOLD. Bipolar output.");sliders[132].setTooltip("LFO / Tempo sync. OFF = free Hz rate, ON = DAW tempo at DIV beats per cycle. Sync phase freezes on stopped transport.");sliders[133].setTooltip("LFO / Sync division in beats. 0:8 1:4 2:2 3:1 4:1/2 5:1/4 6:1/8 7:1/16 8:1/32. Used while SYNC is on.");
 addAndMakeVisible(masterFeedback);masterFeedback.setName("MASTER_FB");masterFeedback.setSliderStyle(juce::Slider::RotaryHorizontalVerticalDrag);masterFeedback.setTextBoxStyle(juce::Slider::TextBoxBelow,false,108,24);masterFeedback.setRange(-99,99,.1);masterFeedback.setDoubleClickReturnValue(true,0);masterAttachment=std::make_unique<SliderAttachment>(p.parameters,"MASTER_FB",masterFeedback);
 addAndMakeVisible(clipper);addAndMakeVisible(dcBlock);addAndMakeVisible(globalPanic);clipper.setName("OUT_CLIP");dcBlock.setName("OUT_DC");globalPanic.setName("PANIC_ALL");
 clipAttachment=std::make_unique<ButtonAttachment>(p.parameters,"OUT_CLIP",clipper);dcAttachment=std::make_unique<ButtonAttachment>(p.parameters,"OUT_DC",dcBlock);globalPanic.onClick=[this]{processor.panicAll();};
 masterFeedback.setTooltip("Output after DC block/clipper returns to the rack input one sample later. Bipolar gain. Can self-oscillate; feedback branch guard +/-4. Bypass cuts the loop.");clipper.setTooltip("Hard output ceiling +/-1 (0 dBFS). No oversampling. Protects samples, not inter-sample peaks. Still active in BYPASS ALL.");dcBlock.setTooltip("10 Hz DC blocker before output clipper; also removes DC from the feedback path. Still active in BYPASS ALL.");globalPanic.setTooltip("Master feedback zero and clear every FX history. Does not mute live input or change slot parameters.");
 setSize(960,860);setResizable(false,false);showSlot(p.selectedSlot.load());startTimerHz(20);
}
MonoJuiceAudioProcessorEditor::~MonoJuiceAudioProcessorEditor(){stopTimer();setLookAndFeel(nullptr);}
void MonoJuiceAudioProcessorEditor::bindControls(){for(int i=0;i<model::count;i++){attachments[i].reset();sliders[i].setName(model::id(selected,model::params[i].id));attachments[i]=std::make_unique<SliderAttachment>(processor.parameters,sliders[i].getName(),sliders[i]);}
 freezeAttachment.reset();midSideAttachment.reset();oversampleAttachment.reset();spectralFreezeAttachment.reset();windowAttachment.reset();modelAttachment.reset();routingAttachment.reset();negativeAAttachment.reset();negativeBAttachment.reset();chorusModeAttachment.reset();
 freezeAttachment=std::make_unique<ButtonAttachment>(processor.parameters,model::id(selected,"G_FREEZE"),freeze);
 midSideAttachment=std::make_unique<ButtonAttachment>(processor.parameters,model::id(selected,"K_MS"),midSide);oversampleAttachment=std::make_unique<ButtonAttachment>(processor.parameters,model::id(selected,"K_OS"),oversample);spectralFreezeAttachment=std::make_unique<ButtonAttachment>(processor.parameters,model::id(selected,"S_FREEZE"),spectralFreeze);windowAttachment=std::make_unique<ComboAttachment>(processor.parameters,model::id(selected,"S_WINDOW"),spectreWindow);
 spectreWindow.setName(model::id(selected,"S_WINDOW"));freeze.setName(model::id(selected,"G_FREEZE"));midSide.setName(model::id(selected,"K_MS"));oversample.setName(model::id(selected,"K_OS"));spectralFreeze.setName(model::id(selected,"S_FREEZE"));
 negativeA.setName(model::id(selected,"K_NEG_A"));negativeB.setName(model::id(selected,"K_NEG_B"));odinRouting.setName(model::id(selected,"K_ROUTING"));
 negativeAAttachment=std::make_unique<ButtonAttachment>(processor.parameters,negativeA.getName(),negativeA);negativeBAttachment=std::make_unique<ButtonAttachment>(processor.parameters,negativeB.getName(),negativeB);routingAttachment=std::make_unique<ComboAttachment>(processor.parameters,odinRouting.getName(),odinRouting);
 chorusMode.setName(model::id(selected,"C_MODE"));chorusModeAttachment=std::make_unique<ComboAttachment>(processor.parameters,chorusMode.getName(),chorusMode);
 modelMenu.clear(juce::dontSendNotification);if(type==4||type==5){modelMenu.addItem(type==4?"ODIN2":"CLASSIC 0.5",1);modelMenu.addItem(type==4?"PARALLELCOMB":"EXTENDED",2);modelMenu.setName(model::id(selected,type==4?"K_MODEL":"S_MODE"));modelAttachment=std::make_unique<ComboAttachment>(processor.parameters,modelMenu.getName(),modelMenu);}
}
void MonoJuiceAudioProcessorEditor::refreshPreset(){const int index=processor.matchingFactoryPreset(selected);presetMenu.setSelectedId(index+1,juce::dontSendNotification);presetMenu.setTooltip(juce::String(factory::description(type,index))+". Load affects only this bank, keeps ON and clears its history. Stop transport for window changes. CUSTOM means parameters differ from factory.");}
void MonoJuiceAudioProcessorEditor::showSlot(int i){selected=juce::jlimit(0,4,i);processor.selectedSlot.store(selected);const auto current=processor.settings().slots[selected];type=current.type;variant=type==4?current.colour.model:(current.spectralExtended?1:0);bindControls();for(int s=0;s<5;s++)tabs[s].setToggleState(s==selected,juce::dontSendNotification);showPage(0);}
void MonoJuiceAudioProcessorEditor::showPage(int value){const int last=lastPage(type,variant);page=juce::jlimit(0,last,value);for(auto& slider:sliders)slider.setVisible(false);
 auto show=[&](int i){sliders[size_t(i)].setVisible(true);};
 auto lfo=[&]{for(int i=130;i<134;i++)show(i);};
 if(type==1){if(page==0)for(int i=0;i<4;i++)show(i);if(page==1){for(int i=65;i<69;i++)show(i);lfo();}}
 else if(type==2){if(page==0)for(int i=4;i<12;i++)show(i);if(page==1){for(int i=69;i<77;i++)show(i);lfo();}}
 else if(type==3){if(page==0)for(int i=12;i<24;i++)show(i);if(page==1)for(int i=77;i<89;i++)show(i);if(page==2)lfo();}
 else if(type==4){if(variant){if(page==0)for(int i=24;i<36;i++)show(i);if(page==1)for(int i=36;i<42;i++)show(i);if(page==2)for(int i=58;i<65;i++)show(i);if(page==3)for(int i=89;i<101;i++)show(i);if(page==4){for(int i=101;i<107;i++)show(i);for(int i=123;i<129;i++)show(i);}if(page==5){show(129);lfo();}}else{if(page==0)for(int i=52;i<61;i++)show(i);if(page==1)for(int i=61;i<65;i++)show(i);if(page==2){for(int i=117;i<123;i++)show(i);for(int i=123;i<129;i++)show(i);}if(page==3){show(129);lfo();}}}
 else if(type==5){if(variant){if(page==0)for(int i=42;i<52;i++)show(i);if(page==1)for(int i=107;i<117;i++)show(i);if(page==2)lfo();}else{if(page==0)for(int i=42;i<44;i++)show(i);if(page==1){show(107);show(108);lfo();}}}
 if(type==2)sliders[7].setTooltip("Chorus / Mix. V2: 0 = clean input at any INP, 127 = full effect, smoothed outside the DSP core. V1: original internal mix, pre-fix sound.");
 const int route=processor.settings().slots[selected].odin.routing;sliders[54].setEnabled(route!=0);sliders[55].setEnabled(route!=0);sliders[56].setEnabled(route==2);
 freeze.setVisible(type==3);metalPreset.setVisible(type==3);midSide.setVisible(type==4&&variant);oversample.setVisible(type==4&&variant);panic.setVisible(type==4);negativeA.setVisible(type==4&&!variant);negativeB.setVisible(type==4&&!variant);odinRouting.setVisible(type==4&&!variant);modelMenu.setVisible(type==4||type==5);
 spectreWindow.setVisible(type==5);spectralFreeze.setVisible(type==5&&variant);chorusMode.setVisible(type==2);previousPage.setVisible(last>0);nextPage.setVisible(last>0);previousPage.setEnabled(page>0);nextPage.setEnabled(page<last);init.setEnabled(type!=0);clear.setEnabled(type!=0);randomise.setEnabled(type!=0);presetMenu.setVisible(type==4||type==5);refreshPreset();moveLeft.setEnabled(selected>0);moveRight.setEnabled(selected<4);resized();repaint();}
void MonoJuiceAudioProcessorEditor::resized(){modelMenu.setBounds(412,185,266,30);odinRouting.setBounds(18,602,194,28);negativeA.setBounds(224,602,90,28);negativeB.setBounds(326,602,90,28);
 masterFeedback.setBounds(204,719,108,91);clipper.setBounds(338,718,140,32);dcBlock.setBounds(502,718,152,32);globalPanic.setBounds(704,714,238,36);presetMenu.setBounds(694,185,248,30);randomise.setBounds(576,640,106,32);bypass.setBounds(784,18,158,32);for(int i=0;i<5;i++){tabs[i].setBounds(18+i*186,84,116,31);enabled[i].setBounds(142+i*186,84,56,31);types[i].setBounds(18+i*186,124,180,34);}
 int at=0;for(int i=0;i<model::count;i++)if(sliders[i].isVisible()){sliders[i].setBounds(18+(at%4)*231+62,248+(at/4)*122,108,91);++at;}
 freeze.setBounds(18,640,106,32);metalPreset.setBounds(134,640,164,32);moveLeft.setBounds(348,640,102,32);moveRight.setBounds(462,640,102,32);clear.setBounds(694,640,118,32);init.setBounds(824,640,118,32);
 midSide.setBounds(18,602,140,28);oversample.setBounds(170,602,120,28);panic.setBounds(434,602,110,28);previousPage.setBounds(708,602,110,28);nextPage.setBounds(832,602,110,28);spectreWindow.setBounds(18,602,208,28);spectralFreeze.setBounds(242,602,184,28);chorusMode.setBounds(18,602,208,28);
}
void MonoJuiceAudioProcessorEditor::timerCallback(){const int selectedNow=juce::jlimit(0,4,processor.selectedSlot.load());const auto current=processor.settings().slots[selectedNow];const int mode=current.type==4?current.colour.model:(current.spectralExtended?1:0);if(selectedNow!=selected||type!=current.type||variant!=mode)showSlot(selectedNow);refreshPreset();for(auto& b:enabled)b.setButtonText(b.getToggleState()?"ON":"OFF");peak=std::max(processor.outputPeak.exchange(0.f),peak*.84f);repaint();}
void MonoJuiceAudioProcessorEditor::paint(juce::Graphics& g){g.fillAll(theme::bg);g.setColour(theme::ink);pixel::text(g,"MONOJUICE",{18,15,700,34},21);pixel::text(g,"FX5 / FIVE SLOTS / LEFT TO RIGHT / REPEAT ANY FX",{18,52,700,20},7);
 for(int i=0;i<5;i++){g.setColour(i==selected?theme::ink:theme::dim);g.drawRect(15+i*186,79,186,84,1);}g.setColour(theme::ink);g.fillRect(18,184,924,32);g.setColour(theme::bg);pixel::text(g,juce::String(selected+1)+" / "+model::typeNames[type],{28,185,275,30},21);
 const char* source[]={"NO PROCESSING","NEW FX / FW PRIMITIVES","OS 1.32B / UNCHANGED CORE","NEW FX / FW PRIMITIVES","UHHYOU PARALLELCOMB 0.2.14","SPECTRUM PIXELATOR / EXTENDED"};if(type!=4&&type!=5)pixel::text(g,source[type],{308,186,370,29},7,true);g.setColour(theme::ink);
 int count=0;for(auto& slider:sliders)if(slider.isVisible())count++;const int rows=(count+3)/4;for(int c=0;c<=4&&rows;c++)pixel::dotted(g,18+c*231,226,18+c*231,226+rows*122);for(int r=0;r<=rows&&rows;r++)pixel::dotted(g,18,226+r*122,942,226+r*122);
 int at=0;for(int i=0;i<model::count;i++)if(sliders[i].isVisible()){const auto& p=model::params[i];pixel::text(g,juce::String(p.label)+(juce::String(p.unit).isEmpty()?"":" "+juce::String(p.unit)),{20+(at%4)*231,230+(at/4)*122,227,20},14,true);++at;}
 if(type==0){pixel::text(g,"CHOOSE AN EFFECT IN THE ROW ABOVE",{54,310,840,32},21);pixel::text(g,"EMPTY IS A ZERO-LATENCY THROUGH CONNECTION",{54,370,840,25},14);pixel::text(g,"FIVE IDENTICAL FX OR ANY MIX. EACH SLOT HAS ITS OWN SETTINGS.",{54,428,850,20},7);}
 if(type==1&&page==0){pixel::text(g,"AUDIO PITCH SHIFT / TWO READ HEADS",{40,388,880,28},14);pixel::text(g,"-24 TO +24 ST / ZERO SHIFT IS TRANSPARENT",{40,434,880,25},14);pixel::text(g,"SHORT WINDOW: GRAINIER. LONG WINDOW: SMOOTHER, MORE TRANSIENT SMEAR.",{40,485,880,22},7);}
 if(type==2&&page==0){pixel::text(g,"ORIGINAL CHORUS DSP AND TABLES ARE UNCHANGED",{35,519,890,25},14);pixel::text(g,"EACH CHORUS SLOT HAS ITS OWN CORE, HISTORY AND RATE ADAPTER",{35,563,890,22},7);}
 if(type==4&&((variant&&page==1)||(!variant&&page==1))){pixel::text(g,"DRIVE / WET RESONANCE / ENVELOPE AND LFO TUNING",{32,505,890,25},14);pixel::text(g,"FEEDBACK ABOVE 25% CAN SELF-OSCILLATE. PANIC CLEARS THE LOOP.",{32,548,890,22},7);}
 if(type==5&&variant&&page==0){pixel::text(g,"0 HIGH=NYQUIST 0 PEAKS=ALL -120=MUTE",{18,640,320,24},7);}
 if(type==5&&!variant&&page==0){pixel::text(g,"CLASSIC / ORIGINAL NATIVE SPECTRE 0.5",{38,391,885,26},14);pixel::text(g,"ONLY PROMINENCE, MIX AND WINDOW AFFECT THIS MODEL",{38,439,885,22},7);pixel::text(g,"EXTENDED CONTROLS ARE STORED BUT NOT PROCESSED",{38,475,885,22},7);}
 if(lastPage(type,variant)>0)pixel::text(g,"PAGE "+juce::String(page+1)+"/"+juce::String(lastPage(type,variant)+1),{556,602,140,28},14,true);
 g.fillRect(18,687,924,2);pixel::text(g,"OUTPUT LOOP",{18,717,165,26},14);pixel::text(g,"FEEDBACK %",{178,696,160,22},14,true);pixel::text(g,"OUTPUT > DC BLOCK > CLIPPER > HOST",{338,764,604,20},7);pixel::text(g,"RETURN: ONE SAMPLE / BYPASS CUTS FEEDBACK",{338,789,604,20},7);g.fillRect(18,827,924,2);pixel::text(g,"MONOJUICE 0.8.0",{18,833,170,17},7);pixel::text(g,juce::String(processor.getSampleRate()/1000,1)+"K / PDC "+juce::String(processor.reportedLatency.load())+" SMP",{188,833,290,17},7);pixel::text(g,"GRAINS "+juce::String(processor.grainCount.load()),{526,833,140,17},7);pixel::text(g,peak>1?"CLIP":"OUT",{762,833,62,17},7);for(int i=0;i<12;i++){juce::Rectangle<int> bar(846+i*8,836,5,10);if(i<int(std::sqrt(std::clamp(peak,0.f,1.f))*12))g.fillRect(bar);else g.drawRect(bar,1);}
}
