#include "dsp/Rack.h"
#include "../Reference/Spectre_0_5_0.h"
#include <iostream>
#include <stdexcept>
#include <chrono>
#include <thread>
#include <cstdlib>
#include <new>
#include <fstream>
#include <functional>
#include <limits>
static bool watch=false;static unsigned allocations=0;
void* operator new(std::size_t n){if(watch)++allocations;if(auto* p=std::malloc(n?n:1))return p;throw std::bad_alloc();}
void* operator new[](std::size_t n){return ::operator new(n);}void operator delete(void* p)noexcept{std::free(p);}void operator delete[](void* p)noexcept{std::free(p);}void operator delete(void* p,std::size_t)noexcept{std::free(p);}void operator delete[](void* p,std::size_t)noexcept{std::free(p);}
void require(bool ok,const char* message){if(!ok)throw std::runtime_error(message);}
using namespace nova;using fx::Frame;
extern "C" {void* combOracleCreate(double);void combOracleDestroy(void*);void combOracleConfigure(void*,const double*,bool);void combOracleProcess(void*,int,const float*,const float*,float*,float*);}
Frame signal(int i,double rate){return {float(.023*std::sin(2*fx::pi*220*i/rate)+.012*std::sin(2*fx::pi*721*i/rate)),float(.028*std::sin(2*fx::pi*331*i/rate))};}
std::array<double,20> oracleValues(const fx::CombSettings& s){auto db=[](float x,float floor){return x<=floor?0.f:std::pow(10.f,x*.05f);};return {{0,s.delayMs[0]*.001f,s.delayMs[1]*.001f,s.delayMs[2]*.001f,s.delayMs[3]*.001f,s.multiplier,s.feedback*.01f,s.highpass,s.limiterMs*.001f,s.rate,s.smoothMs*.001f,s.lean*.01f,s.cross*.01f,s.am,db(s.gateDB,-140),s.gateMs*.001f,db(s.dryDB,-60),db(s.wetDB,-60),s.midSide?1.:0.,s.oversample?1.:0.}};}
int main(int argc,char** argv){try{
 // Compare directly against pinned, unmodified upstream DSPCore, not another comb formula.
 for(double sr:{44100.,48000.,96000.})for(int mode=0;mode<4;mode++){
  fx::CombSettings s;s.delayMs={3.7f,7.1f,11.3f,17.9f};s.feedback=19;s.highpass=35;s.cross=23;s.lean=-17;s.midSide=mode&1;s.oversample=mode&2;s.smoothMs=3;s.gateDB=-90;s.am=.03f;
  fx::ParallelCombModel model;model.prepare(sr);model.set(s);model.reset();void* oracle=combOracleCreate(sr);auto values=oracleValues(s);combOracleConfigure(oracle,values.data(),true);
  std::array<float,257> inL{},inR{},outL{},outR{};double err=0,referenceEnergy=0,difference=0;
  for(int block=0;block<32;block++){if(block==15){s.feedback=22;s.cross=70;model.set(s);values=oracleValues(s);combOracleConfigure(oracle,values.data(),false);}for(int i=0;i<257;i++){auto x=signal(block*257+i,sr);inL[i]=x.l;inR[i]=x.r;}combOracleProcess(oracle,257,inL.data(),inR.data(),outL.data(),outR.data());for(int i=0;i<257;i++){auto y=model.process({inL[i],inR[i]});err=std::max(err,double(std::max(std::abs(y.l-outL[i]),std::abs(y.r-outR[i]))));difference+=std::pow(y.l-outL[i],2)+std::pow(y.r-outR[i],2);referenceEnergy+=outL[i]*outL[i]+outR[i]*outR[i];}}
  combOracleDestroy(oracle);const double rel=std::sqrt(difference/std::max(1e-20,referenceEnergy));std::cout<<"UPSTREAM ParallelComb @ "<<sr<<" mode "<<mode<<" max="<<err<<" relativeRMS="<<rel<<'\n';require(err<2e-6&&rel<1e-5,"upstream comb mismatch");
 }
 // Concurrent instances with different sample rates and oversampling must not share smoothing state.
 auto renderComb=[](double sr,bool os){fx::ParallelCombModel c;c.prepare(sr);fx::CombSettings s;s.oversample=os;s.delayMs={3,5,7,11};s.feedback=17;c.set(s);c.reset();std::vector<Frame> out(6000);for(int i=0;i<6000;i++){if(i==3000){s.feedback=22;c.set(s);}out[i]=c.process(signal(i,sr));}return out;};
 auto expectedA=renderComb(44100,false),expectedB=renderComb(96000,true);std::vector<Frame> a,b;std::thread t1([&]{a=renderComb(44100,false);}),t2([&]{b=renderComb(96000,true);});t1.join();t2.join();for(size_t i=0;i<a.size();i++)require(a[i].l==expectedA[i].l&&b[i].l==expectedB[i].l,"cross-instance smoother interference");std::cout<<"Concurrent different-rate / different-OS comb instances PASS\n";
 fx::MDCTPlans bank;bank.prepare();oldSpectre::MDCTPlans oldBank;oldBank.prepare();fx::Spectre spectre;spectre.prepare(bank,48000);oldSpectre::Spectre old;old.prepare(oldBank);
 for(int w=0;w<8;w++){spectre.set({10,100,w});spectre.reset();old.set({10,100,w});old.reset();int errors=0;for(int i=0;i<(512<<w)*3+100;i++){auto x=signal(i,48000),y=spectre.process(x),z=old.process(x);if(y.l!=z.l||y.r!=z.r)++errors;}require(errors==0,"neutral Spectre changed old sound");std::cout<<"Spectre neutral vs 0.5.0 window "<<(512<<w)<<": 0 sample differences PASS\n";}
 auto spectralRender=[&](fx::SpectreSettings s){spectre.set(s);spectre.reset();std::vector<float> out(12000);std::uint32_t rng=19;for(int i=0;i<int(out.size());i++){rng=rng*1664525u+1013904223u;const auto v=spectre.process({(float(rng>>8)/16777216.f-.5f)*.07f,0});require(v.r==0,"Spectre channel independence");out[i]=v.l;}return out;};
 fx::SpectreSettings base;base.window=0;auto baseline=spectralRender(base);for(int knob=0;knob<8;knob++){auto s=base;switch(knob){case 0:s.low=6000;break;case 1:s.high=1200;break;case 2:s.peaks=3;break;case 3:s.width=4;break;case 4:s.reject=-20;break;case 5:s.attack=200;break;case 6:s.release=300;break;case 7:s.shift=7;break;}auto out=spectralRender(s);double d=0;for(size_t i=0;i<out.size();i++)d+=std::pow(out[i]-baseline[i],2);require(d>1e-7,"inactive new Spectre parameter");std::cout<<"Spectre extension "<<knob<<" difference energy "<<d<<" PASS\n";}
 spectre.set(base);spectre.reset();for(int i=0;i<8000;i++)spectre.process(signal(i,48000));base.freeze=true;spectre.set(base);double freezeEnergy=0;for(int i=0;i<16000;i++){auto y=spectre.process({});if(i>1000)freezeEnergy+=y.l*y.l;}require(freezeEnergy>1e-5,"spectral freeze fails to hold");spectre.reset();double empty=0;for(int i=0;i<3000;i++){auto y=spectre.process(signal(i,48000));empty+=y.l*y.l;}require(empty==0,"empty freeze should not invent capture");std::cout<<"Spectral Freeze holds after silence, empty capture silent PASS\n";
 auto rack=std::make_unique<rack::Rack>();rack::Settings settings;
 for(double rate:{44100.,48000.,96000.}){rack->prepare(rate,settings);AudioAdapter chorus;chorus.prepare(rate);chorus.reset(ChorusCore::defaults);for(int i=0;i<9000;i++){auto x=signal(i,rate),y=rack->process(x);float l,r;chorus.processFrame(x.l,x.r,l,r,false);require(y.l==l&&y.r==r,"unchanged chorus");}
  for(int type=0;type<=5;type++){rack::Settings s;for(auto& slot:s.slots){slot.type=type;slot.on=true;slot.spectre.window=0;slot.comb.feedback=15;slot.grain.mix=30;}rack->reset(s);double energy=0;for(int i=0;i<9000;i++){auto x=signal(i,rate),y=rack->process(x);require(std::isfinite(y.l)&&std::abs(y.l)<32,"five repeats unstable");energy+=y.l*y.l;}require(energy>1e-9,"five repeats silent");}
  for(int mask=0;mask<32;mask++){rack::Settings s;for(int j=0;j<5;j++){s.slots[j].type=j+1;s.slots[j].on=(mask>>j)&1;s.slots[j].spectre.window=0;s.slots[j].comb.feedback=15;}rack->reset(s);for(int i=0;i<1500;i++){auto y=rack->process(signal(i,rate));require(std::isfinite(y.l),"bypass masks");}}
  std::cout<<"CHORUS bit-exact / all five-repeat types / 32 masks @ "<<rate<<" PASS\n";
 }
 std::array<int,5> order{{1,2,3,4,5}};int permutations=0;do{rack::Settings s;for(int j=0;j<5;j++){s.slots[j].type=order[j];s.slots[j].on=true;s.slots[j].spectre.window=0;s.slots[j].comb.feedback=15;}rack->reset(s);for(int i=0;i<3000;i++){auto y=rack->process(signal(i,96000));require(std::isfinite(y.l),"permutation audio");}++permutations;}while(std::next_permutation(order.begin(),order.end()));require(permutations==120,"all permutations");std::cout<<"120 permutations PASS\n";
 rack::Settings dry;for(int j=0;j<5;j++){dry.slots[j].type=j+1;dry.slots[j].on=false;dry.slots[j].spectre.window=0;}rack->prepare(48000,dry);require(rack->latency()==87+512,"PDC sum");for(int i=0;i<5000;i++){auto y=rack->process(signal(i,48000)),x=i>=599?signal(i-599,48000):Frame{};require(x.l==y.l&&x.r==y.r,"aligned all-off dry");}
 watch=true;for(int i=0;i<10000;i++){if(i%127==0)rack->set(dry);rack->process(signal(i,48000));}watch=false;require(allocations==0,"allocation in native processing");std::cout<<"PDC and allocation watchdog PASS\n";
 rack::Slot slot;
 {rack::SlotSettings v1,v2;v1.type=v2.type=rack::Chorus;v1.on=v2.on=true;v1.chorusMode=0;v2.chorusMode=1;slot.prepare(44100,bank,v1);std::vector<float> a;for(int i=0;i<20000;i++)a.push_back(slot.process(signal(i,44100)).l);slot.prepare(44100,bank,v2);for(int i=0;i<20000;i++)require(slot.process(signal(i,44100)).l==a[i],"v1/v2 MIX=127 split");std::cout<<"CHORUS v1==v2 bit-exact at MIX=127 PASS\n";}
 {rack::SlotSettings lo,hi;lo.type=hi.type=rack::Chorus;lo.on=hi.on=true;lo.chorus={64,64,64,0,0,0,127,64};hi.chorus={64,64,64,0,0,0,127,127};slot.prepare(44100,bank,lo);double ea=0;for(int i=0;i<12000;i++){auto y=slot.process(signal(i,44100));if(i>=6000)ea+=y.l*y.l;}slot.prepare(44100,bank,hi);double eb=0;for(int i=0;i<12000;i++){auto y=slot.process(signal(i,44100));if(i>=6000)eb+=y.l*y.l;}require(eb>ea*2.25,"v1 MIX=0 lost INP gain");std::cout<<"CHORUS v1 MIX=0 legacy INP gain PASS\n";}
 {rack::SlotSettings s;s.type=rack::Chorus;s.on=true;s.chorusMode=1;s.chorus={64,64,64,0,0,0,127,64};slot.prepare(44100,bank,s);const int lat=slot.latency();for(int i=0;i<8000;i++){auto y=slot.process(signal(i,44100)),x=i>=lat?signal(i-lat,44100):Frame{};require(y.l==x.l&&y.r==x.r,"v2 MIX=0 not clean");}std::cout<<"CHORUS v2 MIX=0 bit-clean dry PASS\n";}
 auto renders=[&](rack::SlotSettings s){slot.prepare(44100,bank,s);std::vector<float> out(20000);for(int i=0;i<20000;i++){auto y=slot.process(signal(i,44100));require(std::isfinite(y.l)&&std::abs(y.l)<8,"LFO finite");out[std::size_t(i)]=y.l;}return out;};
 auto differs=[&](rack::SlotSettings s,std::function<void(rack::SlotSettings&)> mod,const char* msg){auto a=renders(s);mod(s);auto b=renders(s);double d=0;for(std::size_t i=0;i<a.size();i++)d+=(a[i]-b[i])*(a[i]-b[i]);require(d>1e-6,msg);};
 {rack::SlotSettings s;s.type=rack::Pitch;s.on=true;differs(s,[](rack::SlotSettings& s){s.lfo.pitch[0]=12;},"pitch LFO");}
 {rack::SlotSettings s;s.type=rack::Chorus;s.on=true;s.chorus={64,64,64,100,0,0,127,64};differs(s,[](rack::SlotSettings& s){s.lfo.chorus[1]=60;},"chorus v1 LFO");s.chorusMode=1;differs(s,[](rack::SlotSettings& s){s.lfo.chorus[1]=60;},"chorus v2 LFO");differs(s,[](rack::SlotSettings& s){s.lfo.chorus[3]=100;},"chorus v2 MIX LFO");}
 {rack::SlotSettings s;s.type=rack::Granular;s.on=true;differs(s,[](rack::SlotSettings& s){s.lfo.grain[4]=12;},"grain LFO");}
 {rack::SlotSettings s;s.type=rack::Comb;s.on=true;s.comb.feedback=20;s.colour.model=1;differs(s,[](rack::SlotSettings& s){s.lfo.comb[5]=30;},"parallel LFO");}
 {rack::SlotSettings s;s.type=rack::Comb;s.on=true;s.odin.resA=75;s.colour.model=0;differs(s,[](rack::SlotSettings& s){s.lfo.odin[1]=20;},"odin LFO");}
 {rack::SlotSettings s;s.type=rack::Spectre;s.on=true;s.spectralExtended=true;differs(s,[](rack::SlotSettings& s){s.lfo.spectre[9]=12;},"spectre LFO");}
 {rack::SlotSettings s;s.type=rack::Spectre;s.on=true;s.spectralExtended=false;differs(s,[](rack::SlotSettings& s){s.lfo.spectre[0]=40;},"classic LFO");}
 std::cout<<"LFO matrix affects every effect and model PASS\n";
 {rack::SlotSettings s;s.type=rack::Chorus;s.on=true;s.chorus={64,64,64,100,0,0,127,64};s.chorusMode=1;s.lfo.sync=1;s.lfo.div=2;s.lfo.chorus[1]=60;std::vector<float> a,b;for(int run=0;run<2;run++){slot.prepare(44100,bank,s);double ppq=0;std::vector<float> out;for(int i=0;i<20000;i++){if(i%512==0)slot.setTempo(ppq,120./60/44100,true);out.push_back(slot.process(signal(i,44100)).l);ppq+=120./60/44100;}if(run==0)a=out;else b=out;}require(a==b,"sync determinism");std::cout<<"LFO tempo-sync determinism PASS\n";}
 {rack::SlotSettings s;s.type=rack::Chorus;s.on=true;s.lfo.chorus[1]=60;slot.prepare(44100,bank,s);std::vector<float> a;for(int i=0;i<18000;i++)a.push_back(slot.process(signal(i,44100)).l);slot.prepare(44100,bank,s);for(int i=0;i<18000;i++){if(i%127==0)slot.set(s);require(slot.process(signal(i,44100)).l==a[std::size_t(i)],"LFO block dependence");}std::cout<<"LFO block-independence PASS\n";}
 {const float span[65]={48,200,140,100,127,127,127,127,127,127,127,127,490,79,2000,1000,48,1200,100,100,99.5f,100,15700,100,4000,4000,4000,4000,1,100,24000,16000,4,100000,200,100,100,140,9999.9f,84,120,96,99,100,96000,96000,512,24,120,2000,5000,48,15960,99.5f,15960,99.5f,100,100,36,100,42,24,19.97f,72,1995};
  rack::SlotSettings s;s.on=true;s.lfo.rate=7;for(int type=1;type<=5;type++){s.type=type;s.comb.feedback=15;s.grain.mix=30;s.spectre.window=0;for(int i=0;i<4;i++)s.lfo.pitch[i]=(i%2?1.f:-1.f)*span[i];for(int i=0;i<8;i++)s.lfo.chorus[i]=(i%2?1.f:-1.f)*span[4+i];for(int i=0;i<12;i++)s.lfo.grain[i]=(i%2?1.f:-1.f)*span[12+i];for(int i=0;i<18;i++)s.lfo.comb[i]=(i%2?1.f:-1.f)*span[24+i];for(int i=0;i<6;i++)s.lfo.odin[i]=(i%2?1.f:-1.f)*span[52+i];for(int i=0;i<7;i++)s.lfo.colour[i]=(i%2?1.f:-1.f)*span[58+i];for(int i=0;i<10;i++)s.lfo.spectre[i]=(i%2?1.f:-1.f)*span[42+i];
  for(int variant=0;variant<(type>=4?2:1);variant++){if(type==4)s.colour.model=variant;if(type==5)s.spectralExtended=variant!=0;for(int mode=0;mode<(type==2?2:1);mode++){s.chorusMode=mode;slot.prepare(44100,bank,s);for(int i=0;i<20000;i++){auto y=slot.process(signal(i,44100));require(std::isfinite(y.l)&&std::isfinite(y.r)&&std::abs(y.l)<1e12,"extreme LFO");}}}}std::cout<<"LFO +/-span extremes all types PASS\n";}
 {rack::SlotSettings s;s.type=rack::Comb;s.on=true;s.comb.limiterMs=0;s.colour.model=1;slot.prepare(44100,bank,s);double e=0;for(int i=0;i<12000;i++){auto y=slot.process(signal(i,44100));require(std::isfinite(y.l),"limiter0");if(i>4000)e+=y.l*y.l;}require(e>1e-9,"limiter0 mute");std::cout<<"K_LIM=0 stays finite and audible PASS\n";}
 if(argc>1){rack::Settings s;int types[]={4,1,2,5,3};for(int j=0;j<5;j++){s.slots[j].type=types[j];s.slots[j].on=true;}s.slots[0].comb.delayMs={7.5,11,17,23};s.slots[0].comb.feedback=23;s.slots[0].comb.wetDB=-12;s.slots[1].pitch.semitones=7;s.slots[3].spectre={15,70,2,100,8000,24,2,-36,30,160,0,false};s.slots[4].grain.feedback=95;s.slots[4].grain.sizeMs=180;s.slots[4].grain.density=36;s.slots[4].grain.sprayMs=8;s.slots[4].grain.metal=85;rack->prepare(44100,s);std::ofstream f(argv[1],std::ios::binary);for(int i=0;i<441000;i++){auto x=i<44100*4?signal(i,44100)*float(std::exp(-8.*(i%22050)/44100)):Frame{};auto y=rack->process(x);f.write(reinterpret_cast<const char*>(&y),sizeof y);}}
 std::cout<<"ALL 0.6.0 TESTS PASS\n";return 0;
}catch(const std::exception& e){watch=false;std::cerr<<"FAIL: "<<e.what()<<'\n';return 1;}}
